### ISSUE TITLE
Tratamento de datas

### ISSUE THREAD

**Issue by wagnerssouza** [guilima/financial-back#1]
Talvez usar moment aqui poderia padronizar, e pode ser que tenha que tratar datas em vários lugares.

https://github.com/guilima/financial-back/blob/14714cbf4e423c9070cfdd7c406cb328d1f7bcea/src/business/upsertSeries.business.js#L21

**Comment by guilima** [comment]
Boa

Talvez formalize melhor um moment do que esse código caseiro ratão.
Antes de utilizar a dependência do **moment** estou pensando em usar o [**date-fns**](https://date-fns.org/) que é mais leve. Só não sei se vai atender todos os casos como o moment, por isso vou avaliar.
