### ISSUE TITLE
Domínio

### ISSUE THREAD

**Issue by wagnerssouza** [guilima/financial-back#2]
Nesses casos de listas fixas, na minha opinião, eu não deixaria solto assim dentro do business.

```javascript
  const parse = {
    '4391': 'CDI',
    '433': 'IPCA',
    '189': 'IGP-M',
    '192': 'INCC',
    '7832': 'Ibovespa',
    '7830': 'Ouro',
    '196': 'Poupança',
    '4390': 'SELIC',
    'default': ''
  }
```

Quando falamos de coisas desse tipo, podemos abstrair para uma constante(Enum) ou em uma tabela de domínio em um banco relacional, ou caso o banco seja não-relacional, uma nova collection.

O que vocês acham: @guilima e @diogosalmeida ?

https://github.com/guilima/financial-back/blob/14714cbf4e423c9070cfdd7c406cb328d1f7bcea/src/business/upsertSeries.business.js#L4

**Comment by diogosalmeida** [comment]
Perfeita observação

**Comment by guilima** [comment]
Faz todo o sentido para mim. Vou tentar decidir o que é melhor na situação. Tabela de domínios ou utils com ENUM. Depois de estudar comento a decisão.

**Comment by guilima** [comment]
No meu caso tanto o `enum SeriesAlpha`, como `enum Series` são para intregação com APIs e não cresceriam tanto de tamanho como não teriam alterações constantes.
Talvez um ponto de melhoria seria parar de se apropriar dos IDs referente aos Índices Financeiros do Banco Central e criar uma tabela de domínio com ids próprios para cada Índice.
