### ISSUE TITLE
Abstração de conexão com o banco

### ISSUE THREAD

**Issue by diogosalmeida** [guilima/financial-back#3]
Tenta depois pegar esse seu arquivo de conexão e quebra ele em conector de banco e outro arquivo de acesso direto, tipo para você ter uma camada de domain.

Isso ajuda você separar bem as regras de negócio

- [x] Separar a lógica da conexão do acesso ao banco.
- [x] Criar arquivos para cada dominio ex: Account, User, Promotion

**Comment by guilima** [comment]
o [arquivo](https://github.com/guilima/financial-back/blob/refactor/es6/src/mongodb.js) de conexão deveria ser separado, mas como é esse de acesso direto?
Hoje eu tento adaptar a conexão com algumas variáveis de ambiente o problema é que localhost geralmente não  tem `user` e `password` aí fiz essa gambola mesmo.
```
password ? `mongodb://${user}:${password}@${host}/${database}` : `mongodb://${host}/${database}`
```

**Comment by diogosalmeida** [comment]
Tipo imagine, que o arquivo que conecta no banco deve ser um arquivo chamado "connect" cujo o único objetivo é abrir conexão e fecha-las

Ai você terá para cada domínio um arquivo que acessa esse modulo de conceções, esses domínios devem estar diretamente ligados a lógica de negócio exemplo um arquivo de domain de "User" esse cara irá realizar todas as consultas do banco relacionadas ao "User" e por ai vai

**Comment by guilima** [comment]
Você teria um exemplo para eu entender melhor? A questão de atribuir à um arquivo a conexão/desconexão ao banco de dados está claro. Só não consegui acompanhar a questão de um arquivo para cada domínio.

Porque nesse código o domínio para acesso ao banco de dados está atrelado a variável de ambiente.

**Comment by guilima** [comment]
Separei uma camada data com domínio Series para conectar no banco. @diogosalmeida dá uma força faz um code review se tiver tempo por gentileza no PR aberto: #15
